import * as React from "react"
import * as cUniUX from 'cuniux';
import * as uniUX from 'uniux'
import { appConfig } from "../../components/appConfigs/subcircels.js";

const orgContextMenu = [['Stream App', function () { uniUX.dialog('Apps of the Year 2021', <div>Hiya!</div>, ['Close', function () { alert('hi') }]) }],
['Configure Stream...', function () { alert('hi') }, true],
['Like', function () { alert('hi') }],
['Write a review...', function () { alert('hi') }],
['Report abuse to Circel...', function () { alert('hi') }]]

class Page extends React.Component {
  render() {
    return <body>
      <cUniUX.Main pageType={'columnedApp'} appConfig={appConfig} page={appConfig.pageConfigs.home}>
        <h1 style={{ fontWeight: 900, fontSize: 60 }} id='header1'>
          I'm a header
        </h1><br /><br /><br />

        <span style={{ float: 'left' }}>
          <h3 id='settingsName' style={{ marginTop: '8px', marginBottom: '8px' }} />
          <span className={cUniUX.styles.minorText} id='currentSubcircel' style={{}} />
        </span>
        <p>

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat blandit aliquam etiam erat. Tellus pellentesque eu tincidunt tortor. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Lacinia quis vel eros donec ac odio tempor orci. Proin nibh nisl condimentum id venenatis a condimentum. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Massa sed elementum tempus egestas sed sed risus pretium. Nunc non blandit massa enim nec dui nunc mattis enim. Amet dictum sit amet justo donec enim. Amet aliquam id diam maecenas. Cursus sit amet dictum sit amet justo donec enim. Amet massa vitae tortor condimentum lacinia quis vel eros. Semper eget duis at tellus at urna. Tincidunt eget nullam non nisi est.<br /><br />

          Aenean vel elit scelerisque mauris pellentesque pulvinar. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Ut consequat semper viverra nam libero justo laoreet sit amet. Nunc sed blandit libero volutpat sed cras. Erat velit scelerisque in dictum non consectetur a erat nam. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Sem nulla pharetra diam sit amet. Sed velit dignissim sodales ut. Sed odio morbi quis commodo odio aenean sed. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Orci dapibus ultrices in iaculis nunc sed. Nunc sed blandit libero volutpat sed cras ornare. Est sit amet facilisis magna etiam.<br /><br />

          Lacus luctus accumsan tortor posuere ac ut. Sem viverra aliquet eget sit amet tellus. Cras fermentum odio eu feugiat pretium nibh. Quisque non tellus orci ac auctor augue mauris augue. Est placerat in egestas erat imperdiet sed. Vel facilisis volutpat est velit egestas. Dolor sit amet consectetur adipiscing elit duis tristique. Massa ultricies mi quis hendrerit dolor magna. Sed euismod nisi porta lorem mollis aliquam ut. Et tortor consequat id porta.

          Dictumst quisque sagittis purus sit amet volutpat consequat. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Enim nulla aliquet porttitor lacus luctus. At lectus urna duis convallis. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Est sit amet facilisis magna etiam. Id semper risus in hendrerit. Amet commodo nulla facilisi nullam vehicula. Sit amet justo donec enim. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Volutpat ac tincidunt vitae semper quis lectus nulla at. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Amet nisl suscipit adipiscing bibendum. Purus non enim praesent elementum facilisis leo. Suscipit tellus mauris a diam maecenas sed enim. Elit pellentesque habitant morbi tristique senectus. Libero enim sed faucibus turpis in. Porttitor massa id neque aliquam. Pulvinar etiam non quam lacus suspendisse faucibus. Turpis nunc eget lorem dolor.<br /><br />

          Sagittis aliquam malesuada bibendum arcu vitae elementum. Ullamcorper velit sed ullamcorper morbi. Orci phasellus egestas tellus rutrum tellus pellentesque. Ultricies mi quis hendrerit dolor magna eget est. Sit amet nulla facilisi morbi tempus iaculis. Pretium lectus quam id leo in vitae turpis massa. Proin sed libero enim sed faucibus. Etiam dignissim diam quis enim lobortis scelerisque fermentum. In nulla posuere sollicitudin aliquam ultrices sagittis. Eget aliquet nibh praesent tristique magna sit. Duis ultricies lacus sed turpis tincidunt id aliquet risus. Pharetra massa massa ultricies mi quis hendrerit dolor. Aliquet nibh praesent tristique magna sit amet. Aliquam eleifend mi in nulla posuere.

          Non arcu risus quis varius. Vel pretium lectus quam id leo in vitae turpis. Velit dignissim sodales ut eu sem integer vitae. Gravida arcu ac tortor dignissim convallis aenean et tortor. Blandit aliquam etiam erat velit. Eget gravida cum sociis natoque penatibus. Faucibus et molestie ac feugiat sed. Quis lectus nulla at volutpat diam ut venenatis tellus. Ipsum dolor sit amet consectetur adipiscing. Sit amet est placerat in egestas erat imperdiet. Dui sapien eget mi proin sed libero. Pretium lectus quam id leo in. Tellus mauris a diam maecenas sed enim ut sem. Maecenas pharetra convallis posuere morbi. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Et pharetra pharetra massa massa. Scelerisque eleifend donec pretium vulputate. Ut diam quam nulla porttitor massa id. Convallis a cras semper auctor neque.<br /><br />

          Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Egestas integer eget aliquet nibh. Velit ut tortor pretium viverra suspendisse potenti nullam. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Eu lobortis elementum nibh tellus molestie nunc non blandit. Porttitor lacus luctus accumsan tortor. Lobortis scelerisque fermentum dui faucibus in ornare. Orci porta non pulvinar neque. Et ligula ullamcorper malesuada proin libero nunc. Volutpat est velit egestas dui id ornare arcu odio. Sed elementum tempus egestas sed sed risus pretium. Amet risus nullam eget felis. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Enim sit amet venenatis urna. Risus quis varius quam quisque id. Ac tortor dignissim convallis aenean et tortor at risus. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Pellentesque nec nam aliquam sem et tortor consequat.<br /><br />

          Vitae ultricies leo integer malesuada. Ut placerat orci nulla pellentesque. Integer vitae justo eget magna fermentum iaculis eu non. Libero justo laoreet sit amet. Lectus urna duis convallis convallis tellus. Eget magna fermentum iaculis eu non. Eget egestas purus viverra accumsan in. Arcu risus quis varius quam quisque id. Volutpat odio facilisis mauris sit amet massa vitae tortor. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Nec nam aliquam sem et tortor consequat id.

          Eu ultrices vitae auctor eu augue ut. Vitae aliquet nec ullamcorper sit amet. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Ac ut consequat semper viverra nam libero justo laoreet sit. Nam libero justo laoreet sit amet cursus sit amet dictum. Donec ultrices tincidunt arcu non. Ultrices tincidunt arcu non sodales. Vel pretium lectus quam id. Purus in massa tempor nec feugiat. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Nunc pulvinar sapien et ligula. Pellentesque habitant morbi tristique senectus et. Malesuada fames ac turpis egestas maecenas pharetra. Tristique senectus et netus et malesuada fames ac turpis egestas. Turpis in eu mi bibendum neque egestas congue. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Amet risus nullam eget felis eget nunc. Eu augue ut lectus arcu bibendum.<br /><br />

          In vitae turpis massa sed elementum tempus egestas. Parturient montes nascetur ridiculus mus mauris. Tellus at urna condimentum mattis pellentesque. Enim nunc faucibus a pellentesque sit amet porttitor eget. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Enim ut sem viverra aliquet eget sit. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Ut porttitor leo a diam sollicitudin tempor id eu. Consectetur adipiscing elit duis tristique sollicitudin nibh. Morbi enim nunc faucibus a pellentesque sit amet. Tempus iaculis urna id volutpat. At augue eget arcu dictum. Eu scelerisque felis imperdiet proin fermentum leo. Tempus iaculis urna id volutpat lacus. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Bibendum neque egestas congue quisque egestas diam in arcu. Arcu dui vivamus arcu felis bibendum ut tristique.<br /><br />

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat blandit aliquam etiam erat. Tellus pellentesque eu tincidunt tortor. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Lacinia quis vel eros donec ac odio tempor orci. Proin nibh nisl condimentum id venenatis a condimentum. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Massa sed elementum tempus egestas sed sed risus pretium. Nunc non blandit massa enim nec dui nunc mattis enim. Amet dictum sit amet justo donec enim. Amet aliquam id diam maecenas. Cursus sit amet dictum sit amet justo donec enim. Amet massa vitae tortor condimentum lacinia quis vel eros. Semper eget duis at tellus at urna. Tincidunt eget nullam non nisi est.<br /><br />

          Aenean vel elit scelerisque mauris pellentesque pulvinar. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Ut consequat semper viverra nam libero justo laoreet sit amet. Nunc sed blandit libero volutpat sed cras. Erat velit scelerisque in dictum non consectetur a erat nam. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Sem nulla pharetra diam sit amet. Sed velit dignissim sodales ut. Sed odio morbi quis commodo odio aenean sed. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Orci dapibus ultrices in iaculis nunc sed. Nunc sed blandit libero volutpat sed cras ornare. Est sit amet facilisis magna etiam.<br /><br />

          Lacus luctus accumsan tortor posuere ac ut. Sem viverra aliquet eget sit amet tellus. Cras fermentum odio eu feugiat pretium nibh. Quisque non tellus orci ac auctor augue mauris augue. Est placerat in egestas erat imperdiet sed. Vel facilisis volutpat est velit egestas. Dolor sit amet consectetur adipiscing elit duis tristique. Massa ultricies mi quis hendrerit dolor magna. Sed euismod nisi porta lorem mollis aliquam ut. Et tortor consequat id porta.

          Dictumst quisque sagittis purus sit amet volutpat consequat. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Enim nulla aliquet porttitor lacus luctus. At lectus urna duis convallis. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Est sit amet facilisis magna etiam. Id semper risus in hendrerit. Amet commodo nulla facilisi nullam vehicula. Sit amet justo donec enim. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Volutpat ac tincidunt vitae semper quis lectus nulla at. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Amet nisl suscipit adipiscing bibendum. Purus non enim praesent elementum facilisis leo. Suscipit tellus mauris a diam maecenas sed enim. Elit pellentesque habitant morbi tristique senectus. Libero enim sed faucibus turpis in. Porttitor massa id neque aliquam. Pulvinar etiam non quam lacus suspendisse faucibus. Turpis nunc eget lorem dolor.<br /><br />

          Sagittis aliquam malesuada bibendum arcu vitae elementum. Ullamcorper velit sed ullamcorper morbi. Orci phasellus egestas tellus rutrum tellus pellentesque. Ultricies mi quis hendrerit dolor magna eget est. Sit amet nulla facilisi morbi tempus iaculis. Pretium lectus quam id leo in vitae turpis massa. Proin sed libero enim sed faucibus. Etiam dignissim diam quis enim lobortis scelerisque fermentum. In nulla posuere sollicitudin aliquam ultrices sagittis. Eget aliquet nibh praesent tristique magna sit. Duis ultricies lacus sed turpis tincidunt id aliquet risus. Pharetra massa massa ultricies mi quis hendrerit dolor. Aliquet nibh praesent tristique magna sit amet. Aliquam eleifend mi in nulla posuere.

          Non arcu risus quis varius. Vel pretium lectus quam id leo in vitae turpis. Velit dignissim sodales ut eu sem integer vitae. Gravida arcu ac tortor dignissim convallis aenean et tortor. Blandit aliquam etiam erat velit. Eget gravida cum sociis natoque penatibus. Faucibus et molestie ac feugiat sed. Quis lectus nulla at volutpat diam ut venenatis tellus. Ipsum dolor sit amet consectetur adipiscing. Sit amet est placerat in egestas erat imperdiet. Dui sapien eget mi proin sed libero. Pretium lectus quam id leo in. Tellus mauris a diam maecenas sed enim ut sem. Maecenas pharetra convallis posuere morbi. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Et pharetra pharetra massa massa. Scelerisque eleifend donec pretium vulputate. Ut diam quam nulla porttitor massa id. Convallis a cras semper auctor neque.<br /><br />

          Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Egestas integer eget aliquet nibh. Velit ut tortor pretium viverra suspendisse potenti nullam. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Eu lobortis elementum nibh tellus molestie nunc non blandit. Porttitor lacus luctus accumsan tortor. Lobortis scelerisque fermentum dui faucibus in ornare. Orci porta non pulvinar neque. Et ligula ullamcorper malesuada proin libero nunc. Volutpat est velit egestas dui id ornare arcu odio. Sed elementum tempus egestas sed sed risus pretium. Amet risus nullam eget felis. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Enim sit amet venenatis urna. Risus quis varius quam quisque id. Ac tortor dignissim convallis aenean et tortor at risus. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Pellentesque nec nam aliquam sem et tortor consequat.<br /><br />

          Vitae ultricies leo integer malesuada. Ut placerat orci nulla pellentesque. Integer vitae justo eget magna fermentum iaculis eu non. Libero justo laoreet sit amet. Lectus urna duis convallis convallis tellus. Eget magna fermentum iaculis eu non. Eget egestas purus viverra accumsan in. Arcu risus quis varius quam quisque id. Volutpat odio facilisis mauris sit amet massa vitae tortor. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Nec nam aliquam sem et tortor consequat id.

          <uniUX.SmallCard style={{ background: 'linear-gradient(180deg, rgba(0,160,231,0.6) 0%, rgba(0,160,231,1) 100%)', color: 'white' }} children={<span>
            <h1><uniUX.FontAwesomeIcon style={{ fontSize: 50 }} icon={uniUX.brandIcons.faTwitter} /></h1>
            <h3 style={{ float: 'left', marginTop: '8px' }}>@viggobf</h3>
            <uniUX.Button type='custom' style={{ color: 'black', backgroundColor: 'white', float: 'right' }} text='Follow'></uniUX.Button>

          </span>} />

          <uniUX.SmallCard style={{ background: 'linear-gradient(180deg, rgba(233, 77, 135, 0.6) 0%, rgba(233, 77, 135, 1) 100%)', color: 'white' }} children={<span>
            <h1><uniUX.FontAwesomeIcon style={{ fontSize: 50 }} icon={uniUX.brandIcons.faDribbble} /></h1>
            <h3 style={{ float: 'left', marginTop: '8px' }}>@viggobf</h3>
            <uniUX.Button type='custom' style={{ color: 'black', backgroundColor: 'white', float: 'right' }} text='Follow'></uniUX.Button>

          </span>} />

          <uniUX.SmallCard style={{ background: 'linear-gradient(180deg, rgba(41, 41, 41, 0.6) 0%, rgb(41, 41, 41) 100%)', color: 'white' }} children={<span>
            <h1><uniUX.FontAwesomeIcon style={{ fontSize: 50 }} icon={uniUX.brandIcons.faMedium} /></h1>
            <h3 style={{ float: 'left', marginTop: '8px' }}>@viggobf</h3>
            <uniUX.Button type='custom' style={{ color: 'black', backgroundColor: 'white', float: 'right' }} text='Follow'>Follow</uniUX.Button>

          </span>} />
          Eu ultrices vitae auctor eu augue ut. Vitae aliquet nec ullamcorper sit amet. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Ac ut consequat semper viverra nam libero justo laoreet sit. Nam libero justo laoreet sit amet cursus sit amet dictum. Donec ultrices tincidunt arcu non. Ultrices tincidunt arcu non sodales. Vel pretium lectus quam id. Purus in massa tempor nec feugiat. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Nunc pulvinar sapien et ligula. Pellentesque habitant morbi tristique senectus et. Malesuada fames ac turpis egestas maecenas pharetra. Tristique senectus et netus et malesuada fames ac turpis egestas. Turpis in eu mi bibendum neque egestas congue. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Amet risus nullam eget felis eget nunc. Eu augue ut lectus arcu bibendum.<br /><br />

          In vitae turpis massa sed elementum tempus egestas. Parturient montes nascetur ridiculus mus mauris. Tellus at urna condimentum mattis pellentesque. Enim nunc faucibus a pellentesque sit amet porttitor eget. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Enim ut sem viverra aliquet eget sit. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Ut porttitor leo a diam sollicitudin tempor id eu. Consectetur adipiscing elit duis tristique sollicitudin nibh. Morbi enim nunc faucibus a pellentesque sit amet. Tempus iaculis urna id volutpat. At augue eget arcu dictum. Eu scelerisque felis imperdiet proin fermentum leo. Tempus iaculis urna id volutpat lacus. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Bibendum neque egestas congue quisque egestas diam in arcu. Arcu dui vivamus arcu felis bibendum ut tristique.<br /><br />

          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat blandit aliquam etiam erat. Tellus pellentesque eu tincidunt tortor. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Lacinia quis vel eros donec ac odio tempor orci. Proin nibh nisl condimentum id venenatis a condimentum. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Massa sed elementum tempus egestas sed sed risus pretium. Nunc non blandit massa enim nec dui nunc mattis enim. Amet dictum sit amet justo donec enim. Amet aliquam id diam maecenas. Cursus sit amet dictum sit amet justo donec enim. Amet massa vitae tortor condimentum lacinia quis vel eros. Semper eget duis at tellus at urna. Tincidunt eget nullam non nisi est.<br /><br />

          Aenean vel elit scelerisque mauris pellentesque pulvinar. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Ut consequat semper viverra nam libero justo laoreet sit amet. Nunc sed blandit libero volutpat sed cras. Erat velit scelerisque in dictum non consectetur a erat nam. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Sem nulla pharetra diam sit amet. Sed velit dignissim sodales ut. Sed odio morbi quis commodo odio aenean sed. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Orci dapibus ultrices in iaculis nunc sed. Nunc sed blandit libero volutpat sed cras ornare. Est sit amet facilisis magna etiam.<br /><br />

          Lacus luctus accumsan tortor posuere ac ut. Sem viverra aliquet eget sit amet tellus. Cras fermentum odio eu feugiat pretium nibh. Quisque non tellus orci ac auctor augue mauris augue. Est placerat in egestas erat imperdiet sed. Vel facilisis volutpat est velit egestas. Dolor sit amet consectetur adipiscing elit duis tristique. Massa ultricies mi quis hendrerit dolor magna. Sed euismod nisi porta lorem mollis aliquam ut. Et tortor consequat id porta.

          Dictumst quisque sagittis purus sit amet volutpat consequat. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Enim nulla aliquet porttitor lacus luctus. At lectus urna duis convallis. Quis enim lobortis scelerisque fermentum dui faucibus in ornare quam. Est sit amet facilisis magna etiam. Id semper risus in hendrerit. Amet commodo nulla facilisi nullam vehicula. Sit amet justo donec enim. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Volutpat ac tincidunt vitae semper quis lectus nulla at. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Amet nisl suscipit adipiscing bibendum. Purus non enim praesent elementum facilisis leo. Suscipit tellus mauris a diam maecenas sed enim. Elit pellentesque habitant morbi tristique senectus. Libero enim sed faucibus turpis in. Porttitor massa id neque aliquam. Pulvinar etiam non quam lacus suspendisse faucibus. Turpis nunc eget lorem dolor.<br /><br />

          Sagittis aliquam malesuada bibendum arcu vitae elementum. Ullamcorper velit sed ullamcorper morbi. Orci phasellus egestas tellus rutrum tellus pellentesque. Ultricies mi quis hendrerit dolor magna eget est. Sit amet nulla facilisi morbi tempus iaculis. Pretium lectus quam id leo in vitae turpis massa. Proin sed libero enim sed faucibus. Etiam dignissim diam quis enim lobortis scelerisque fermentum. In nulla posuere sollicitudin aliquam ultrices sagittis. Eget aliquet nibh praesent tristique magna sit. Duis ultricies lacus sed turpis tincidunt id aliquet risus. Pharetra massa massa ultricies mi quis hendrerit dolor. Aliquet nibh praesent tristique magna sit amet. Aliquam eleifend mi in nulla posuere.

          Non arcu risus quis varius. Vel pretium lectus quam id leo in vitae turpis. Velit dignissim sodales ut eu sem integer vitae. Gravida arcu ac tortor dignissim convallis aenean et tortor. Blandit aliquam etiam erat velit. Eget gravida cum sociis natoque penatibus. Faucibus et molestie ac feugiat sed. Quis lectus nulla at volutpat diam ut venenatis tellus. Ipsum dolor sit amet consectetur adipiscing. Sit amet est placerat in egestas erat imperdiet. Dui sapien eget mi proin sed libero. Pretium lectus quam id leo in. Tellus mauris a diam maecenas sed enim ut sem. Maecenas pharetra convallis posuere morbi. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Et pharetra pharetra massa massa. Scelerisque eleifend donec pretium vulputate. Ut diam quam nulla porttitor massa id. Convallis a cras semper auctor neque.<br /><br />

          Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Egestas integer eget aliquet nibh. Velit ut tortor pretium viverra suspendisse potenti nullam. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Eu lobortis elementum nibh tellus molestie nunc non blandit. Porttitor lacus luctus accumsan tortor. Lobortis scelerisque fermentum dui faucibus in ornare. Orci porta non pulvinar neque. Et ligula ullamcorper malesuada proin libero nunc. Volutpat est velit egestas dui id ornare arcu odio. Sed elementum tempus egestas sed sed risus pretium. Amet risus nullam eget felis. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Enim sit amet venenatis urna. Risus quis varius quam quisque id. Ac tortor dignissim convallis aenean et tortor at risus. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Pellentesque nec nam aliquam sem et tortor consequat.<br /><br />

          Vitae ultricies leo integer malesuada. Ut placerat orci nulla pellentesque. Integer vitae justo eget magna fermentum iaculis eu non. Libero justo laoreet sit amet. Lectus urna duis convallis convallis tellus. Eget magna fermentum iaculis eu non. Eget egestas purus viverra accumsan in. Arcu risus quis varius quam quisque id. Volutpat odio facilisis mauris sit amet massa vitae tortor. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Nec nam aliquam sem et tortor consequat id.

          Eu ultrices vitae auctor eu augue ut. Vitae aliquet nec ullamcorper sit amet. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Ac ut consequat semper viverra nam libero justo laoreet sit. Nam libero justo laoreet sit amet cursus sit amet dictum. Donec ultrices tincidunt arcu non. Ultrices tincidunt arcu non sodales. Vel pretium lectus quam id. Purus in massa tempor nec feugiat. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Nunc pulvinar sapien et ligula. Pellentesque habitant morbi tristique senectus et. Malesuada fames ac turpis egestas maecenas pharetra. Tristique senectus et netus et malesuada fames ac turpis egestas. Turpis in eu mi bibendum neque egestas congue. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Amet risus nullam eget felis eget nunc. Eu augue ut lectus arcu bibendum.<br /><br />

          In vitae turpis massa sed elementum tempus egestas. Parturient montes nascetur ridiculus mus mauris. Tellus at urna condimentum mattis pellentesque. Enim nunc faucibus a pellentesque sit amet porttitor eget. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Enim ut sem viverra aliquet eget sit. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Ut porttitor leo a diam sollicitudin tempor id eu. Consectetur adipiscing elit duis tristique sollicitudin nibh. Morbi enim nunc faucibus a pellentesque sit amet. Tempus iaculis urna id volutpat. At augue eget arcu dictum. Eu scelerisque felis imperdiet proin fermentum leo. Tempus iaculis urna id volutpat lacus. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Bibendum neque egestas congue quisque egestas diam in arcu. Arcu dui vivamus arcu felis bibendum ut tristique.<br /><br />
        </p>
      </cUniUX.Main>
    </body>
  }
}

export default Page
